# Generated by Django 4.2 on 2024-10-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('new_message', 'New Message'), ('friend_request_accepted', 'Friend Request Accepted')], max_length=100),
        ),
    ]
