# Generated by Django 4.2 on 2024-10-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_actioned',
            field=models.BooleanField(default=False),
        ),
    ]
