# Generated by Django 4.2 on 2024-11-02 12:45

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_roomchat_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchat',
            name='name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=255, unique=True),
        ),
    ]
