# Generated by Django 4.2 on 2024-11-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_reportpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportpost',
            old_name='is_blocked',
            new_name='is_resolve',
        ),
        migrations.AddField(
            model_name='post',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
