# Generated by Django 4.2 on 2024-11-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_rename_is_blocked_reportpost_is_resolve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='follower',
        ),
    ]
