# Generated by Django 4.2 on 2024-11-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_rename_user_follow_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('new_message', 'New Message'), ('friend_request_accepted', 'Friend Request Accepted'), ('liked_post', 'Liked Post')], max_length=100),
        ),
    ]
