# Generated by Django 4.2 on 2024-11-06 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='social.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('new_message', 'New Message'), ('friend_request_accepted', 'Friend Request Accepted'), ('liked_post', 'Liked Post'), ('commented_post', 'Commented Post')], max_length=100),
        ),
    ]
