# Generated by Django 4.2 on 2024-11-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_notification_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
