# Generated by Django 4.2 on 2024-11-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
