# Generated by Django 4.2 on 2024-11-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_remove_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
