# Generated by Django 4.2 on 2024-11-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_alter_groupmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('public', 'Public'), ('friends', 'Friends')], default='public', max_length=20),
        ),
    ]
