# Generated by Django 4.2 on 2024-11-24 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0026_post_page_delete_pagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='admins',
            field=models.ManyToManyField(related_name='admin_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
